### ISSUE TITLE
Delaying the jobs to be run

### ISSUE THREAD

**Issue by wzul** [10up/WP-Minions#35]
I need to delay the queue to 30 seconds before it's run.

Is any method I can use or just use sleep() function from PHP?

Thanks

**Comment by cmmarslender** [comment]
WP Minions is built and designed to run the async jobs as soon as possible once they are added to the queue. `sleep()` would work, but it would also block any other jobs in the queue from running, since your runner(s) would be tied up just sleeping. You could also create a single WP Cron task scheduled for 30 seconds later, and then use the WP Cron callback to schedule the async job to the queue to avoid blocking any other jobs in your job queue.
